# This workflow deploys the app to workers ðŸš€
name: Production Deployment
on:
    push:
        branches:
            - trunk

# Cancel previous instances of this workflow
concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
    cancel-in-progress: true

env:
    CLOUDFLARE_API_TOKEN: "${{ secrets.CF_API_TOKEN }}"
    MAYTAPI_PRODUCT: "${{ secrets.MAYTAPI_PRODUCT }}"
    MAYTAPI_PHONE: "${{ secrets.MAYTAPI_PHONE }}"
    MAYTAPI_TOKEN: "${{ secrets.MAYTAPI_TOKEN }}"

jobs:
    deploy:
        name: Production Deploy
        runs-on: ubuntu-latest
        timeout-minutes: 30
        environment:
            name: Production
            url: ${{ steps.deploy.outputs.url }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3.4.0
            - uses: ./.github/actions/ci_setup
            - name: Deploy
              id: deploy
              run: |
                  set -ex -o pipefail
                  exec 3>&1
                  npm i -g wrangler
                  URL=$(wrangler publish | tee /dev/fd/3 | grep 'workers.dev' | head -n 1 | xargs)
                  echo "âœ… URL: $URL"
                  if ! HOOK=$(curl "https://api.maytapi.com/api/${MAYTAPI_PRODUCT}/setWebhook" \
                                   --header "Content-Type: application/json" \
                                   --header "Accept: application/json" \
                                   --header "x-maytapi-key: ${MAYTAPI_TOKEN}" \
                                   --data "{ \"webhook\": \"${URL}/hook\" }" | tee /dev/fd/3); then
                      echo "âŒ FAILED TO UPDATE HOOK"
                  fi
                  exec 3>&-
                  echo "url=$URL" >> $GITHUB_OUTPUT
